[package]
name = "sqp"
description = """
The squishiest image format!
"""
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
integer-encoding = "4.0.0"
rayon = "1.10.0"
thiserror = "1.0.63"
